export const projectsDeatails = [
  {
    id: 1,
    demo: true,
    title: "Clemeset",
    description: "Admin platform to manage farmers & customers.",
    tools: ["Next.js", "Tailwind CSS", "Ai"],
    image: "../clemeset.svg",
    live: "https://your-live-link.com",
    github: "https://github.com/yourname/farmconnect",
    category: "nextjs",
  },
  {
    id: 2,
    demo: false,
    title: "FarmConnect",
    description: "Admin platform to manage farmers & customers.",
    tools: ["Next.js", "Tailwind CSS", "Node.js"],
    image: " ../farmlogo.png",
    live: "https://farmconnect-admin.vercel.app/dashboard",
    github: "https://github.com/OluwaseunSodeeq/farmconnect",
    category: "nextjs",
  },
  {
    id: 3,
    demo: false,
    title: "LearnApp",
    description: "Responsive business site showcasing services.",
    tools: ["Next.js", "Tailwind CSS", "Python"],
    image: "../Eisoft-Logo.png",
    live: "https://learnapp-beta.vercel.app/dashboard/",
    github: "https://github.com/OluwaseunSodeeq/learnapp",
    category: "nextjs",
  },
  {
    id: 4,
    demo: false,
    title: "BES – Engineering Services",
    description:
      "Responsive business site showcasing services. business site showcasing services.",
    tools: ["React.js", "Tailwind CSS", "Formspree"],
    image: "../BESLOGO.svg",
    live: "https://bes-beta.vercel.app/",
    github: "https://github.com/OluwaseunSodeeq/bes",
    category: "reactjs",
  },
  {
    id: 5,
    demo: false,
    title: "Abdul-gafar-portfolio",
    description: "Responsive business site showcasing services.",
    tools: ["React.js", "Tailwind CSS", "EmailJS"],
    image: "../Eisoft-Logo.png",
    live: "https://abdul-gafar.netlify.app/",
    github: "https://github.com/OluwaseunSodeeq/abdul-gafar-portfolio",
    category: "reactjs",
  },
  {
    id: 6,
    demo: false,
    title: "Little Lemon",
    description: "Responsive business site showcasing services.",
    tools: ["React.js", "Styled-Components", "Formik & Yup, Git"],
    image: "../lemon-logo.svg",
    live: "https://little-lemon-indol.vercel.app/",
    github: "https://github.com/OluwaseunSodeeq/little-lemon",
    category: "reactjs",
  },
  {
    id: 7,
    demo: false,
    title: "Tiide Cuisine",
    description: "Responsive business site showcasing services.",
    tools: ["CSS", "HTML", "JavaScript"],
    image: "../tiide-logo.webp",
    live: "https://tiide-cuisine.netlify.app/",
    github: "https://github.com/OluwaseunSodeeq/TFP---tiide_cuisine",
    category: "vanillajs",
  },

  {
    id: 8,
    demo: false,
    title: "IP-Address-Tracker",
    description: "Responsive business site showcasing services.",
    tools: ["HTML & CSS", "JavaScript", "Leaflet.js"],
    image: "../frontendMentor-removebg.png",
    live: "https://oluwaseunsodeeq.github.io/ip-address-tracker/",
    github: "https://github.com/OluwaseunSodeeq/ip-address-tracker",
    category: "vanillajs",
  },
  {
    id: 9,
    demo: false,
    title: "Expense Tracker",
    description: "Responsive business site showcasing services.",
    tools: ["CSS", "HTML", "JavaScript"],
    image: "../Eisoft-Logo.png",
    live: "https://osexpensetracker.netlify.app/",
    github: "https://github.com/OluwaseunSodeeq/expensetracker",
    category: "vanillajs",
  },
];
