export const projectsDeatails = [
  {
    id: 1,
    demo: true,
    title: "Clemeset",
    description:
      "A climate literacy platform designed to promote environmental awareness through storytelling and technology. Includes an AI chatbot that provides accurate insights on climate, weather, and sustainability topics.",
    tools: ["Next.js", "Tailwind CSS", "Ai"],
    image: "../clemeset.svg",
    live: "https://alyika.vercel.app/",
    github: "https://github.com/OluwaseunSodeeq/alyika",
    category: "nextjs",
  },
  {
    id: 2,
    demo: false,
    title: "FarmConnect",
    description:
      "An admin-driven platform built to manage interactions between farmers and buyers efficiently. Features a structured dashboard for monitoring products, users, and transaction-related data.",
    tools: ["Next.js", "Tailwind CSS", "Node.js"],
    image: "../farmlogo.png",
    live: "https://farmconnect-admin.vercel.app/dashboard",
    github: "https://github.com/OluwaseunSodeeq/farmconnect",
    category: "nextjs",
  },
  {
    id: 3,
    demo: false,
    title: "LearnApp",
    description:
      "A digital school platform that enables students to access learning resources and institutional information. Built to improve engagement while simplifying communication within the academic environment.",
    tools: ["Next.js", "Tailwind CSS", "Python"],
    image: "../Eisoft-Logo.png",
    live: "https://learnapp-beta.vercel.app/dashboard/",
    github: "https://github.com/OluwaseunSodeeq/learnapp",
    category: "nextjs",
  },
  {
    id: 4,
    demo: false,
    title: "BES – Engineering Services",
    description:
      "A responsive corporate website developed to showcase engineering services and completed projects. Integrates a contact workflow that enables potential clients to reach the business seamlessly.",
    tools: ["React.js", "Tailwind CSS", "Formspree"],
    image: "../BESLOGO.svg",
    live: "https://bes-beta.vercel.app/",
    github: "https://github.com/OluwaseunSodeeq/bes",
    category: "reactjs",
  },
  {
    id: 5,
    demo: false,
    title: "Abdul-gafar-portfolio",
    description:
      "A professional portfolio website built for a UI/UX designer to showcase expertise and services. Designed to communicate credibility, creativity, and value to potential clients.",
    tools: ["React.js", "Tailwind CSS", "EmailJS"],
    image: "../Eisoft-Logo.png",
    live: "https://abdul-gafar.netlify.app/",
    github: "https://github.com/OluwaseunSodeeq/abdul-gafar-portfolio",
    category: "reactjs",
  },
  {
    id: 6,
    demo: false,
    title: "Little Lemon",
    description:
      "A restaurant web application that allows customers to view menus and place orders online. Improves customer experience by streamlining ordering and reducing in-person wait times.",
    tools: ["React.js", "Styled-Components", "Formik & Yup, Git"],
    image: "../lemon-logo.svg",
    live: "https://little-lemon-indol.vercel.app/",
    github: "https://github.com/OluwaseunSodeeq/little-lemon",
    category: "reactjs",
  },
  {
    id: 7,
    demo: false,
    title: "Tiide Cuisine",
    description:
      "A responsive cuisine website built to showcase food offerings and business services. Helps establish a strong online presence and attract new customers effectively.",
    tools: ["CSS", "HTML", "JavaScript"],
    image: "../tiide-logo.webp",
    live: "https://tiide-cuisine.netlify.app/",
    github: "https://github.com/OluwaseunSodeeq/TFP---tiide_cuisine",
    category: "vanilla javascript",
  },
  {
    id: 8,
    demo: false,
    title: "IP-Address-Tracker",
    description:
      "A web tool that validates IP addresses and displays real-time geolocation data. Built with clear error handling to ensure accuracy and a smooth user experience.",
    tools: ["HTML & CSS", "JavaScript", "Leaflet.js"],
    image: "../frontendMentor-removebg.png",
    live: "https://oluwaseunsodeeq.github.io/ip-address-tracker/",
    github: "https://github.com/OluwaseunSodeeq/ip-address-tracker",
    category: "vanilla javascript",
  },
  {
    id: 9,
    demo: false,
    title: "Expense Tracker",
    description:
      "A lightweight expense tracking application designed to record and calculate daily spending. Helps users maintain financial awareness through a simple and intuitive interface.",
    tools: ["CSS", "HTML", "JavaScript"],
    image: "../Eisoft-Logo.png",
    live: "https://osexpensetracker.netlify.app/",
    github: "https://github.com/OluwaseunSodeeq/expensetracker",
    category: "vanilla javascript",
  },
];
